//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Watch {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLib_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLib_en() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Watch.StringLib_en", typeof(StringLib_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddAlarm {
            get {
                return ResourceManager.GetString("AddAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlarmList {
            get {
                return ResourceManager.GetString("AlarmList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlarmName {
            get {
                return ResourceManager.GetString("AlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input is empty. Please enter a value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CheckName {
            get {
                return ResourceManager.GetString("CheckName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clock과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day Repeat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DayRepeat {
            get {
                return ResourceManager.GetString("DayRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter a New Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EnterANewName {
            get {
                return ResourceManager.GetString("EnterANewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fri과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Record과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat Days과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RepeatDays {
            get {
                return ResourceManager.GetString("RepeatDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Timer Duration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SetTimerDuration {
            get {
                return ResourceManager.GetString("SetTimerDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StopWatch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StopWatch {
            get {
                return ResourceManager.GetString("StopWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sun과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time Diff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TimeDifference {
            get {
                return ResourceManager.GetString("TimeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Timer {
            get {
                return ResourceManager.GetString("Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
